server:
  build: nginx/ 
  ports:
   - "80"
   - "443"
  volumes_from:
   - src-worst-things
  links:
   - php1
php1:
  build: php/
  volumes_from:
   - src-worst-things
  links:
   - posgres
posgres:
  build: posgres/
